### PR TITLE
Delete AdoptionFrom , Create template Forms

### PR DESCRIPTION
**Pull request by PauloSoVieira**
Deleted all files from adoption Form + FormFields and deleted the connection with AdoptionRequest.
Created Simple form.
FormFields to add forms.
Create AdoptionForm with Json

### CODE REVIEW

**Comment by PauloSoVieira** [comment]
waiting-for-pull

**Comment by PauloSoVieira** [comment]
r_2880659_Vum14

**Review by ruitiago23 — APPROVED** [review]
Top deleter!

**Review by rui-tx — APPROVED** [review]
looksgood

**Pull request merged**
